name: C/C++ CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build C++
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14]

    steps:
    - uses: actions/checkout@v3

    - name: Update gcc
      if : matrix.os == 'macos-14'
      run: |
        brew install gcc
        brew link --overwrite gcc

    - name: make
      run: |
        cd src/lib
        make

